#!/bin/sh
# /etc/init.d/weatherstation
### BEGIN INIT INFO
# Provides:          weatherstation
# Required-Start:    $network
# Required-Stop:
# Default-Start:     2 3 5
# Default-Stop:      0 1 6
# Short-Description: weatherstation
# Description:
### END INIT INFO

case "$1" in
start)
cd /home/pi/Weatherstation
echo "get remote CSVs"
sudo -u pi scp raspberrypi-outside:/home/pi/wetterstation/*.csv ./
echo "Starting weatherstation and send it to background ..."
java -jar Weatherstation-1.0-SNAPSHOT.jar  &

;;
stop)
echo "shutting down Weatherstation ..."
kill `jps -l | grep Weatherstation | awk '{print $1}'`
;;
*)
echo "Usage: /etc/init.d/weatherstation {start|stop}"
exit 1
;;
esac
exit 0
