#!/bin/sh
# /etc/init.d/weatherstation
### BEGIN INIT INFO
# Provides:          weatherstation
# Required-Start:    $network
# Required-Stop:
# Default-Start:     2 3 5
# Default-Stop:      0 1 6
# Short-Description: weatherstation
# Description:
### END INIT INFO

. /lib/lsb/init-functions

case "$1" in
start) log_daemon_msg "starting weatherstation" "weatherstation"
        cd /home/pi/Weatherstation
        log_daemon_msg "get remote CSVs" "weatherstation"
        sudo -u pi scp raspberrypi-outside:/home/pi/wetterstation/*.csv ./
        log_daemon_msg "Starting weatherstation and send it to background ..." "weatherstation"
        nice -n 7  java -jar Weatherstation-1.0-SNAPSHOT.jar  &
        sleep 120
        nice -n 15 java -cp Weatherstation-1.0-SNAPSHOT.jar de.locked.webexporter.Exporter &
;;
stop) log_daemon_msg "stopping weatherstation" "weatherstation"
        kill `jps -l | grep Weatherstation | awk '{print $1}'`
        kill `jps -l | grep Exporter | awk '{print $1}'`
;;
restart)
        $0 stop
        $0 start
;;
*)
echo "Usage: /etc/init.d/weatherstation {start|stop}"
exit 1
;;
esac
exit 0
