#!/bin/sh
# /etc/init.d/x11vnc
### BEGIN INIT INFO
# Provides:          x11vnc
# Required-Start:    lightdm
# Required-Stop:
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: x11vnc
# Description:
### END INIT INFO

case "$1" in
start)
echo "Starting x11vnc ... "
x11vnc -auth /var/run/lightdm/root/:0 -rfbauth /root/.vnc/passwd -no6 -noipv6 -reopen -forever -shared

;;
stop)
echo "Killing x11vnc ..."
killall x11vnc
;;
*)
echo "Usage: /etc/init.d/x11vnc {start|stop}"
exit 1
;;
esac
exit 0


